extends:
  - 'eslint:recommended'

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 8

rules:
  no-lone-blocks: 0
  no-throw-literal: 0
  no-console: 0
  no-case-declarations: 0
  no-fallthrough: 0
  no-sparse-arrays: 0
  no-unused-vars: 1